// Catalogue complet des points des quatorze canaux.
//
// data.js porte une sélection commentée de 95 points ; ce fichier ajoute tous
// les autres, pour atteindre la nomenclature standard de l'OMS : 361 points.
// Chaque entrée porte sa règle de localisation, dans le même système de cun que
// scripts/point-rules.js, et scripts/place-points.js la convertit en position
// sur le maillage.
//
//   id, nom (pinyin), trad (sens du nom), info (catégorie et indications),
//   r (règle de localisation).
//
// Les catégories classiques : Jing-puits, Ying-source, Shu-ruisseau,
// Jing-rivière, He-mer (les cinq points Shu antiques), Yuan (source),
// Luo (passage), Xi (fissure), Mu (alarme, sur le ventre), Shu du dos.

const CATALOGUE = {

// ---------------------------------------------------------------- Poumon
LU: [
  { id: 'LU2', name: 'Yunmen', trad: 'Porte des Nuages', info: "Creux sous la clavicule. Toux, oppression, douleur d'épaule.",
    r: { zone: 'torse', from: 'CV22', cun: 1.0, lat: 6.0, face: 'front' } },
  { id: 'LU3', name: 'Tianfu', trad: 'Palais Céleste', info: "Épistaxis, essoufflement, tristesse.",
    r: { zone: 'bras', cun: 3.0, angle: 40 } },
  { id: 'LU4', name: 'Xiabai', trad: 'Blanc Serré', info: "Oppression thoracique, douleur du bras.",
    r: { zone: 'bras', cun: 4.0, angle: 40 } },
  { id: 'LU8', name: 'Jingqu', trad: 'Passage du Méridien', info: "Point Jing-rivière. Toux, asthme, douleur du poignet.",
    r: { zone: 'bras', cun: 20.0, angle: 70 } },
],

// --------------------------------------------------------- Gros Intestin
LI: [
  { id: 'LI2', name: 'Erjian', trad: 'Second Intervalle', info: "Point Ying-source. Mal de gorge, mal de dents, fièvre.",
    r: { zone: 'main', doigt: 2, t: 0.15, cote: 'radial', face: 'dos' } },
  { id: 'LI3', name: 'Sanjian', trad: 'Troisième Intervalle', info: "Point Shu-ruisseau. Mal de dents, gorge, douleur de la main.",
    r: { zone: 'main', avance: 0.52, entre: [2], decal: -0.012 } },
  { id: 'LI5', name: 'Yangxi', trad: 'Ravin du Yang', info: "Point Jing-rivière, dans la tabatière anatomique. Poignet, céphalée, dents.",
    r: { zone: 'bras', cun: 21.0, angle: 115 } },
  { id: 'LI6', name: 'Pianli', trad: 'Passage Oblique', info: "Point Luo. Œdème, acouphènes, épistaxis.",
    r: { zone: 'bras', cun: 18.0, angle: 120 } },
  { id: 'LI7', name: 'Wenliu', trad: 'Courant Tiède', info: "Point Xi. Douleur abdominale, gorge, borborygmes.",
    r: { zone: 'bras', cun: 16.0, angle: 120 } },
  { id: 'LI8', name: 'Xialian', trad: 'Angle Inférieur', info: "Douleur du coude et de l'avant-bras.",
    r: { zone: 'bras', cun: 13.0, angle: 125 } },
  { id: 'LI9', name: 'Shanglian', trad: 'Angle Supérieur', info: "Douleur de l'épaule et du bras, hémiplégie.",
    r: { zone: 'bras', cun: 12.0, angle: 125 } },
  { id: 'LI12', name: 'Zhouliao', trad: 'Creux du Coude', info: "Douleur du coude, engourdissement du bras.",
    r: { zone: 'bras', cun: 8.0, angle: 130 } },
  { id: 'LI13', name: 'Shouwuli', trad: 'Cinq Lieues du Bras', info: "Douleur du coude, adénopathie.",
    r: { zone: 'bras', cun: 6.0, angle: 130 } },
  { id: 'LI16', name: 'Jugu', trad: 'Grand Os', info: "Entre acromion et épine de la scapula. Épaule, bras.",
    r: { zone: 'epaule', angle: 60, versLeCou: 0.82 } },
  { id: 'LI17', name: 'Tianding', trad: 'Trépied Céleste', info: "Extinction de voix, mal de gorge, goitre.",
    r: { zone: 'cou', h: 0.28, lat: 0.9 } },
  { id: 'LI18', name: 'Futu', trad: 'Soutien en Saillie', info: "Sur le sterno-cléido-mastoïdien. Toux, gorge, goitre.",
    r: { zone: 'cou', h: 0.58, lat: 0.9 } },
  { id: 'LI19', name: 'Kouheliao', trad: 'Creux de la Bouche', info: "Épistaxis, nez bouché, paralysie faciale.",
    r: { zone: 'tete', h: 0.28, lat: 0.14, face: 'front' } },
],

// -------------------------------------------------------------- Estomac
ST: [
  { id: 'ST3', name: 'Juliao', trad: 'Grand Creux', info: "Aplomb de la pupille, niveau de l'aile du nez. Paralysie faciale, sinusite.",
    r: { zone: 'tete', h: 0.34, lat: 0.31, face: 'front' } },
  { id: 'ST4', name: 'Dicang', trad: 'Grenier Terrestre', info: "Au coin de la bouche. Paralysie faciale, bavage, névralgie.",
    r: { zone: 'tete', h: 0.19, lat: 0.26, face: 'front' } },
  { id: 'ST5', name: 'Daying', trad: 'Grand Accueil', info: "Devant l'angle de la mâchoire, sur l'artère faciale. Trismus, joue enflée.",
    r: { zone: 'tete', h: 0.16, lat: 0.62, face: 'side', avance: 0.55 } },
  { id: 'ST7', name: 'Xiaguan', trad: 'Barrière Inférieure', info: "Sous l'arcade zygomatique. Articulation de la mâchoire, otalgie, dents.",
    r: { zone: 'tete', h: 0.40, lat: 0.92, face: 'side', avance: 0.35 } },
  { id: 'ST9', name: 'Renying', trad: 'Accueil de l’Homme', info: "Sur la carotide. Hypertension, goitre, gorge. Ne jamais piquer profondément.",
    r: { zone: 'cou', h: 0.52, lat: 0.55 } },
  { id: 'ST10', name: 'Shuitu', trad: 'Passage de l’Eau', info: "Mal de gorge, toux, asthme.",
    r: { zone: 'cou', h: 0.32, lat: 0.6 } },
  { id: 'ST11', name: 'Qishe', trad: 'Demeure du Souffle', info: "Base du cou, bord supérieur de la clavicule. Gorge, goitre, hoquet.",
    r: { zone: 'cou', h: 0.08, lat: 0.6 } },
  { id: 'ST12', name: 'Quepen', trad: 'Bassin Brisé', info: "Dans le creux sus-claviculaire. Toux, asthme, gorge.",
    r: { zone: 'torse', from: 'CV22', cun: -0.4, lat: 4.0, face: 'front' } },
  { id: 'ST13', name: 'Qihu', trad: 'Porte du Souffle', info: "Sous la clavicule, 4 cun de la médiane. Toux, oppression.",
    r: { zone: 'torse', from: 'CV22', cun: 1.0, lat: 4.0, face: 'front' } },
  { id: 'ST14', name: 'Kufang', trad: 'Chambre du Grenier', info: "1er espace intercostal. Toux, douleur thoracique.",
    r: { zone: 'torse', from: 'CV22', cun: 2.4, lat: 4.0, face: 'front' } },
  { id: 'ST15', name: 'Wuyi', trad: 'Paravent du Toit', info: "2e espace intercostal. Oppression, mastite.",
    r: { zone: 'torse', from: 'CV22', cun: 4.0, lat: 4.0, face: 'front' } },
  { id: 'ST16', name: 'Yingchuang', trad: 'Fenêtre de la Poitrine', info: "3e espace intercostal. Toux, mastite.",
    r: { zone: 'torse', from: 'CV22', cun: 5.4, lat: 4.0, face: 'front' } },
  { id: 'ST17', name: 'Ruzhong', trad: 'Centre du Sein', info: "Au centre du mamelon. Repère de mesure seulement : ni aiguille ni moxa.",
    r: { zone: 'torse', from: 'CV22', cun: 6.8, lat: 4.0, face: 'front' } },
  { id: 'ST18', name: 'Rugen', trad: 'Racine du Sein', info: "5e espace intercostal. Mastite, insuffisance de lait, toux.",
    r: { zone: 'torse', from: 'CV22', cun: 8.2, lat: 4.0, face: 'front' } },
  { id: 'ST19', name: 'Burong', trad: 'Refus de Contenir', info: "6 cun au-dessus du nombril, 2 cun de la médiane. Vomissements, douleur gastrique.",
    r: { zone: 'torse', from: 'nombril', cun: -6.0, lat: 2.0, face: 'front' } },
  { id: 'ST20', name: 'Chengman', trad: 'Réceptacle de la Plénitude', info: "5 cun au-dessus du nombril. Distension, douleur gastrique.",
    r: { zone: 'torse', from: 'nombril', cun: -5.0, lat: 2.0, face: 'front' } },
  { id: 'ST21', name: 'Liangmen', trad: 'Porte de la Poutre', info: "4 cun au-dessus du nombril. Douleur gastrique, inappétence.",
    r: { zone: 'torse', from: 'nombril', cun: -4.0, lat: 2.0, face: 'front' } },
  { id: 'ST22', name: 'Guanmen', trad: 'Porte de la Barrière', info: "3 cun au-dessus du nombril. Ballonnement, diarrhée.",
    r: { zone: 'torse', from: 'nombril', cun: -3.0, lat: 2.0, face: 'front' } },
  { id: 'ST23', name: 'Taiyi', trad: 'Grande Unité', info: "2 cun au-dessus du nombril. Agitation mentale, digestion.",
    r: { zone: 'torse', from: 'nombril', cun: -2.0, lat: 2.0, face: 'front' } },
  { id: 'ST24', name: 'Huaroumen', trad: 'Porte de la Chair Glissante', info: "1 cun au-dessus du nombril. Vomissements, langue raide.",
    r: { zone: 'torse', from: 'nombril', cun: -1.0, lat: 2.0, face: 'front' } },
  { id: 'ST26', name: 'Wailing', trad: 'Tertre Extérieur', info: "1 cun sous le nombril. Douleur abdominale, dysménorrhée.",
    r: { zone: 'torse', from: 'nombril', cun: 1.0, lat: 2.0, face: 'front' } },
  { id: 'ST27', name: 'Daju', trad: 'Grande Grandeur', info: "2 cun sous le nombril. Distension, troubles urinaires.",
    r: { zone: 'torse', from: 'nombril', cun: 2.0, lat: 2.0, face: 'front' } },
  { id: 'ST28', name: 'Shuidao', trad: 'Voie des Eaux', info: "3 cun sous le nombril. Rétention d'urine, œdème, règles.",
    r: { zone: 'torse', from: 'nombril', cun: 3.0, lat: 2.0, face: 'front' } },
  { id: 'ST29', name: 'Guilai', trad: 'Retour', info: "4 cun sous le nombril. Aménorrhée, descente d'organe.",
    r: { zone: 'torse', from: 'nombril', cun: 4.0, lat: 2.0, face: 'front' } },
  { id: 'ST30', name: 'Qichong', trad: 'Assaut du Souffle', info: "5 cun sous le nombril, au bord du pubis. Génital, hernie.",
    r: { zone: 'torse', from: 'nombril', cun: 5.0, lat: 2.0, face: 'front' } },
  { id: 'ST31', name: 'Biguan', trad: 'Barrière de la Hanche', info: "Pli de l'aine, sur le couturier. Douleur de hanche, paralysie.",
    r: { zone: 'jambe', cun: 1.0, angle: 40 } },
  { id: 'ST32', name: 'Futu', trad: 'Lièvre Tapi', info: "6 cun au-dessus de la rotule. Douleur de cuisse, faiblesse.",
    r: { zone: 'jambe', cun: 12.0, angle: 25 } },
  { id: 'ST33', name: 'Yinshi', trad: 'Marché du Yin', info: "3 cun au-dessus de la rotule. Genou raide, froid des jambes.",
    r: { zone: 'jambe', cun: 15.0, angle: 25 } },
  { id: 'ST34', name: 'Liangqiu', trad: 'Tertre de la Poutre', info: "Point Xi. 2 cun au-dessus de la rotule. Douleur gastrique aiguë, genou.",
    r: { zone: 'jambe', cun: 16.0, angle: 25 } },
  { id: 'ST35', name: 'Dubi', trad: 'Nez du Veau', info: "Creux externe sous la rotule. Douleur et gonflement du genou.",
    r: { zone: 'jambe', cun: 18.5, angle: 45 } },
  { id: 'ST37', name: 'Shangjuxu', trad: 'Grand Vide Supérieur', info: "Point He inférieur du Gros Intestin. 6 cun sous le genou. Diarrhée, appendicite.",
    r: { zone: 'jambe', cun: 24.0, angle: 30 } },
  { id: 'ST38', name: 'Tiaokou', trad: 'Ouverture Étroite', info: "8 cun sous le genou. Épaule bloquée, douleur de jambe.",
    r: { zone: 'jambe', cun: 26.0, angle: 30 } },
  { id: 'ST39', name: 'Xiajuxu', trad: 'Grand Vide Inférieur', info: "Point He inférieur de l'Intestin Grêle. 9 cun sous le genou.",
    r: { zone: 'jambe', cun: 27.0, angle: 30 } },
  { id: 'ST41', name: 'Jiexi', trad: 'Ravin de la Dislocation', info: "Point Jing-rivière. Au pli de la cheville, entre les tendons. Entorse, céphalée.",
    r: { zone: 'jambe', cun: 34.0, angle: 10 } },
  { id: 'ST42', name: 'Chongyang', trad: 'Assaut du Yang', info: "Point Yuan. Sur le dos du pied, au point le plus haut. Inappétence, paralysie faciale.",
    r: { zone: 'pied', avance: 0.52, entre: [2] } },
  { id: 'ST43', name: 'Xiangu', trad: 'Vallée Enfoncée', info: "Point Shu-ruisseau. Entre 2e et 3e métatarsiens. Œdème du visage, douleur abdominale.",
    r: { zone: 'pied', avance: 0.66, entre: [2, 3] } },
],

// ------------------------------------------------------------------ Rate
SP: [
  { id: 'SP2', name: 'Dadu', trad: 'Grande Capitale', info: "Point Ying-source. Distension abdominale, fièvre sans transpiration.",
    r: { zone: 'pied', orteil: 1, t: 0.15, cote: 'medial' } },
  { id: 'SP4', name: 'Gongsun', trad: 'Petit-fils du Prince', info: "Point Luo, clé du Chong Mai. Douleur gastrique, règles, nausées.",
    r: { zone: 'pied', avance: 0.52, entre: [1], decal: -0.012, face: 'bordOppose' } },
  { id: 'SP5', name: 'Shangqiu', trad: 'Tertre du Métal', info: "Point Jing-rivière. Distension, langueur, entorse de cheville.",
    r: { zone: 'jambe', cun: 34.0, angle: 285, bas: 0.6 } },
  { id: 'SP7', name: 'Lougu', trad: 'Vallée qui Fuit', info: "Ballonnement, froid et lourdeur des jambes.",
    r: { zone: 'jambe', cun: 28.0, angle: 255 } },
  { id: 'SP8', name: 'Diji', trad: 'Ressort de la Terre', info: "Point Xi. Dysménorrhée, digestion, œdème.",
    r: { zone: 'jambe', cun: 22.5, angle: 258 } },
  { id: 'SP11', name: 'Jimen', trad: 'Porte du Tamis', info: "Rétention d'urine, douleur de la cuisse interne.",
    r: { zone: 'jambe', cun: 10.0, angle: 280 } },
  { id: 'SP12', name: 'Chongmen', trad: 'Porte de l’Assaut', info: "Pli de l'aine. Hernie, rétention, douleur pelvienne.",
    r: { zone: 'torse', from: 'nombril', cun: 5.0, lat: 3.5, face: 'front' } },
  { id: 'SP13', name: 'Fushe', trad: 'Demeure de l’Abdomen', info: "Douleur abdominale, hernie.",
    r: { zone: 'torse', from: 'nombril', cun: 4.3, lat: 4.0, face: 'front' } },
  { id: 'SP14', name: 'Fujie', trad: 'Nœud de l’Abdomen', info: "Diarrhée, douleur péri-ombilicale.",
    r: { zone: 'torse', from: 'nombril', cun: 1.3, lat: 4.0, face: 'front' } },
  { id: 'SP15', name: 'Daheng', trad: 'Grande Transversale', info: "À hauteur du nombril, 4 cun de la médiane. Constipation, diarrhée.",
    r: { zone: 'torse', from: 'nombril', cun: 0, lat: 4.0, face: 'front' } },
  { id: 'SP16', name: 'Fu’ai', trad: 'Lamentation de l’Abdomen', info: "Digestion difficile, douleur gastrique.",
    r: { zone: 'torse', from: 'nombril', cun: -3.0, lat: 4.0, face: 'front' } },
  { id: 'SP17', name: 'Shidou', trad: 'Cavité des Aliments', info: "5e espace intercostal. Oppression, régurgitations.",
    r: { zone: 'torse', from: 'CV22', cun: 8.2, lat: 6.0, face: 'front' } },
  { id: 'SP18', name: 'Tianxi', trad: 'Ruisseau Céleste', info: "4e espace intercostal. Mastite, toux.",
    r: { zone: 'torse', from: 'CV22', cun: 6.8, lat: 6.0, face: 'front' } },
  { id: 'SP19', name: 'Xiongxiang', trad: 'Village de la Poitrine', info: "3e espace intercostal. Douleur thoracique.",
    r: { zone: 'torse', from: 'CV22', cun: 5.4, lat: 6.0, face: 'front' } },
  { id: 'SP20', name: 'Zhourong', trad: 'Circulation Complète', info: "2e espace intercostal. Toux, oppression.",
    r: { zone: 'torse', from: 'CV22', cun: 4.0, lat: 6.0, face: 'front' } },
],

// ------------------------------------------------------------------ Cœur
HT: [
  { id: 'HT2', name: 'Qingling', trad: 'Esprit Bleu-vert', info: "Douleur du bras et de l'épaule, ictère.",
    r: { zone: 'bras', cun: 6.0, angle: 320 } },
  { id: 'HT4', name: 'Lingdao', trad: 'Voie de l’Esprit', info: "Point Jing-rivière. Palpitations, aphonie soudaine, coude.",
    r: { zone: 'bras', cun: 19.5, angle: 305 } },
  { id: 'HT6', name: 'Yinxi', trad: 'Fissure du Yin', info: "Point Xi. Sueurs nocturnes, palpitations, épistaxis.",
    r: { zone: 'bras', cun: 20.5, angle: 305 } },
  { id: 'HT8', name: 'Shaofu', trad: 'Petit Palais', info: "Point Ying-source. Palpitations, angoisse, prurit génital.",
    r: { zone: 'main', avance: 0.50, entre: [4, 5], face: 'palmaire' } },
],

// -------------------------------------------------------- Intestin Grêle
SI: [
  { id: 'SI2', name: 'Qiangu', trad: 'Vallée Antérieure', info: "Point Ying-source. Fièvre, acouphènes, mal de gorge.",
    r: { zone: 'main', doigt: 5, t: 0.15, cote: 'ulnaire', face: 'dos' } },
  { id: 'SI4', name: 'Wangu', trad: 'Os du Poignet', info: "Point Yuan. Ictère, raideur de nuque, poignet.",
    r: { zone: 'main', avance: 0.72, entre: [5], decal: 0.010, face: 'bord' } },
  { id: 'SI5', name: 'Yanggu', trad: 'Vallée du Yang', info: "Point Jing-rivière. Douleur du poignet, acouphènes, fièvre.",
    r: { zone: 'bras', cun: 21.0, angle: 240 } },
  { id: 'SI6', name: 'Yanglao', trad: 'Soutien du Vieillard', info: "Point Xi. Baisse de vue, douleur d'épaule et de dos.",
    r: { zone: 'bras', cun: 20.0, angle: 225 } },
  { id: 'SI7', name: 'Zhizheng', trad: 'Branche Droite', info: "Point Luo. Raideur de nuque, coude, agitation.",
    r: { zone: 'bras', cun: 16.0, angle: 235 } },
  { id: 'SI9', name: 'Jianzhen', trad: 'Épaule Vraie', info: "Au-dessus du pli axillaire postérieur. Périarthrite, bras.",
    r: { zone: 'epaule', angle: 205 } },
  { id: 'SI10', name: 'Naoshu', trad: 'Assentiment de l’Épaule', info: "Sous l'épine de la scapula. Douleur et faiblesse d'épaule.",
    r: { zone: 'epaule', angle: 185 } },
  { id: 'SI12', name: 'Bingfeng', trad: 'Saisi par le Vent', info: "Au milieu de la fosse sus-épineuse. Épaule bloquée.",
    r: { zone: 'dos', vertebre: 'T2', lat: 3.6, face: 'back' } },
  { id: 'SI13', name: 'Quyuan', trad: 'Mur Courbe', info: "Bord interne de la fosse sus-épineuse. Épaule, dos.",
    r: { zone: 'dos', vertebre: 'T2', lat: 2.6, face: 'back' } },
  { id: 'SI14', name: 'Jianwaishu', trad: 'Assentiment Externe de l’Épaule', info: "3 cun de T1. Douleur scapulaire, nuque froide.",
    r: { zone: 'dos', vertebre: 'T1', lat: 3.0, face: 'back' } },
  { id: 'SI15', name: 'Jianzhongshu', trad: 'Assentiment Médian de l’Épaule', info: "2 cun de C7. Toux, épaule, vue.",
    r: { zone: 'dos', vertebre: 'C7b', lat: 2.0, face: 'back' } },
  { id: 'SI16', name: 'Tianchuang', trad: 'Fenêtre Céleste', info: "Bord postérieur du SCM. Acouphènes, gorge, torticolis.",
    r: { zone: 'cou', h: 0.5, lat: 1.05 } },
  { id: 'SI17', name: 'Tianrong', trad: 'Apparence Céleste', info: "Derrière l'angle de la mâchoire. Gorge, oreille, goitre.",
    r: { zone: 'cou', h: 0.74, lat: 1.0 } },
],

// -------------------------------------------------------- Maître du Cœur
PC: [
  { id: 'PC1', name: 'Tianchi', trad: 'Étang Céleste', info: "4e espace intercostal, 1 cun en dehors du mamelon. Oppression, mastite.",
    r: { zone: 'torse', from: 'CV22', cun: 6.8, lat: 5.0, face: 'front' } },
  { id: 'PC2', name: 'Tianquan', trad: 'Source Céleste', info: "2 cun sous le pli axillaire antérieur. Douleur cardiaque, bras.",
    r: { zone: 'bras', cun: 2.0, angle: 0 } },
  { id: 'PC4', name: 'Ximen', trad: 'Porte de la Fissure', info: "Point Xi. 5 cun au-dessus du poignet. Douleur cardiaque aiguë, hémoptysie.",
    r: { zone: 'bras', cun: 16.0, angle: 0 } },
  { id: 'PC5', name: 'Jianshi', trad: 'Intermédiaire', info: "Point Jing-rivière. 3 cun au-dessus du poignet. Palpitations, estomac, esprit.",
    r: { zone: 'bras', cun: 18.0, angle: 0 } },
],

// ---------------------------------------------------- Triple Réchauffeur
TE: [
  { id: 'TE1', name: 'Guanchong', trad: 'Assaut de la Barrière', info: "Point Jing-puits. Angle de l'ongle de l'annulaire, côté ulnaire. Fièvre, gorge.",
    r: { zone: 'main', doigt: 4, t: 0.92, cote: 'ulnaire', face: 'dos' } },
  { id: 'TE2', name: 'Yemen', trad: 'Porte des Liquides', info: "Point Ying-source. Entre annulaire et auriculaire. Céphalée, gorge, main.",
    r: { zone: 'main', avance: 0.68, entre: [4, 5] } },
  { id: 'TE4', name: 'Yangchi', trad: 'Étang du Yang', info: "Point Yuan. Au pli dorsal du poignet. Poignet, soif, acouphènes.",
    r: { zone: 'bras', cun: 21.0, angle: 180 } },
  { id: 'TE6', name: 'Zhigou', trad: 'Fossé de la Branche', info: "3 cun au-dessus du poignet, face dorsale. Constipation, douleur costale.",
    r: { zone: 'bras', cun: 18.0, angle: 180 } },
  { id: 'TE7', name: 'Huizong', trad: 'Réunion des Ancêtres', info: "Point Xi. Surdité, épilepsie, douleur du bras.",
    r: { zone: 'bras', cun: 18.0, angle: 200 } },
  { id: 'TE8', name: 'Sanyangluo', trad: 'Réunion des Trois Yang', info: "4 cun au-dessus du poignet. Surdité brusque, aphonie.",
    r: { zone: 'bras', cun: 17.0, angle: 180 } },
  { id: 'TE9', name: 'Sidu', trad: 'Quatre Fleuves', info: "5 cun sous l'olécrâne. Surdité, mal de dents, avant-bras.",
    r: { zone: 'bras', cun: 14.0, angle: 180 } },
  { id: 'TE10', name: 'Tianjing', trad: 'Puits Céleste', info: "Point He-mer. 1 cun au-dessus de l'olécrâne. Coude, adénopathie, migraine.",
    r: { zone: 'bras', cun: 10.0, angle: 190 } },
  { id: 'TE11', name: 'Qinglengyuan', trad: 'Abîme Frais', info: "2 cun au-dessus de l'olécrâne. Douleur d'épaule et de bras.",
    r: { zone: 'bras', cun: 9.0, angle: 190 } },
  { id: 'TE12', name: 'Xiaoluo', trad: 'Dispersion du Réseau', info: "Milieu du bras, face postérieure. Raideur de nuque, céphalée.",
    r: { zone: 'bras', cun: 7.0, angle: 190 } },
  { id: 'TE13', name: 'Naohui', trad: 'Réunion du Bras', info: "3 cun sous l'acromion. Épaule, goitre, bras.",
    r: { zone: 'bras', cun: 5.0, angle: 190 } },
  { id: 'TE15', name: 'Tianliao', trad: 'Creux Céleste', info: "Angle supérieur de la scapula. Épaule et nuque raides.",
    r: { zone: 'epaule', angle: 250, versLeCou: 0.68 } },
  { id: 'TE16', name: 'Tianyou', trad: 'Fenêtre Céleste', info: "Derrière le SCM, sous la mastoïde. Surdité, vue trouble, nuque.",
    r: { zone: 'cou', h: 0.82, lat: 1.0 } },
  { id: 'TE18', name: 'Qimai', trad: 'Vaisseau Convulsif', info: "Derrière l'oreille, au tiers inférieur de la mastoïde. Acouphènes, convulsions.",
    r: { zone: 'tete', h: 0.36, lat: 0.94, face: 'side', avance: -0.25 } },
  { id: 'TE19', name: 'Luxi', trad: 'Repos de la Tête', info: "Derrière l'oreille, au tiers supérieur. Céphalée, otalgie.",
    r: { zone: 'tete', h: 0.46, lat: 0.90, face: 'side', avance: -0.3 } },
  { id: 'TE20', name: 'Jiaosun', trad: 'Angle du Petit-fils', info: "Au-dessus de l'oreille, à la pointe du pavillon. Migraine, dents, œil.",
    r: { zone: 'tete', h: 0.58, lat: 0.88, face: 'side', avance: -0.1 } },
  { id: 'TE21', name: 'Ermen', trad: 'Porte de l’Oreille', info: "Devant l'échancrure du tragus, bouche ouverte. Acouphènes, otite, dents.",
    r: { zone: 'tete', h: 0.47, lat: 0.95, face: 'side', avance: 0.2 } },
  { id: 'TE22', name: 'Erheliao', trad: 'Creux de l’Oreille', info: "Devant l'oreille, sur l'artère temporale. Migraine, acouphènes.",
    r: { zone: 'tete', h: 0.55, lat: 0.9, face: 'side', avance: 0.3 } },
],

// ------------------------------------------------------------------ Foie
LR: [
  { id: 'LR4', name: 'Zhongfeng', trad: 'Sceau du Milieu', info: "Point Jing-rivière. Devant la malléole interne. Hernie, rétention, cheville.",
    r: { zone: 'jambe', cun: 34.0, angle: 300, bas: 0.4 } },
  { id: 'LR5', name: 'Ligou', trad: 'Rainure du Bois', info: "Point Luo. 5 cun au-dessus de la malléole interne. Génital, règles, prurit.",
    r: { zone: 'jambe', cun: 29.0, angle: 265 } },
  { id: 'LR6', name: 'Zhongdu', trad: 'Capitale du Milieu', info: "Point Xi. 7 cun au-dessus de la malléole interne. Douleur abdominale, métrorragie.",
    r: { zone: 'jambe', cun: 27.0, angle: 265 } },
  { id: 'LR7', name: 'Xiguan', trad: 'Barrière du Genou', info: "Sous le condyle interne du tibia. Douleur du genou, gorge.",
    r: { zone: 'jambe', cun: 20.0, angle: 265 } },
  { id: 'LR9', name: 'Yinbao', trad: 'Enveloppe du Yin', info: "4 cun au-dessus du condyle interne. Règles irrégulières, urines.",
    r: { zone: 'jambe', cun: 14.0, angle: 275 } },
  { id: 'LR10', name: 'Zuwuli', trad: 'Cinq Lieues du Pied', info: "3 cun sous ST30, face interne de la cuisse. Distension du bas-ventre.",
    r: { zone: 'jambe', cun: 3.0, angle: 285 } },
  { id: 'LR11', name: 'Yinlian', trad: 'Angle du Yin', info: "2 cun sous ST30. Règles irrégulières, stérilité.",
    r: { zone: 'jambe', cun: 2.0, angle: 285 } },
  { id: 'LR12', name: 'Jimai', trad: 'Vaisseau Urgent', info: "Pli de l'aine, en dehors du pubis. Hernie, douleur génitale.",
    r: { zone: 'torse', from: 'nombril', cun: 5.0, lat: 2.5, face: 'front' } },
  { id: 'LR13', name: 'Zhangmen', trad: 'Porte du Système', info: "Point Mu de la Rate, à la pointe de la 11e côte. Digestion, distension, hypochondre.",
    r: { zone: 'torse', from: 'nombril', cun: -2.0, lat: 6.0, face: 'side' } },
],

// ---------------------------------------------------------------- Vessie
BL: [
  { id: 'BL3', name: 'Meichong', trad: 'Assaut du Sourcil', info: "Céphalée, vertige, nez bouché.",
    r: { zone: 'tete', h: 0.74, lat: 0.19, face: 'front' } },
  { id: 'BL4', name: 'Quchai', trad: 'Divergence Courbe', info: "Céphalée frontale, sinusite, épistaxis.",
    r: { zone: 'tete', h: 0.74, lat: 0.3, face: 'front' } },
  { id: 'BL5', name: 'Wuchu', trad: 'Cinquième Endroit', info: "Céphalée, vertige, convulsions.",
    r: { zone: 'tete', h: 0.79, lat: 0.3, face: 'front' } },
  { id: 'BL6', name: 'Chengguang', trad: 'Réception de la Lumière', info: "Céphalée, nez bouché, vue trouble.",
    r: { zone: 'tete', h: 0.86, lat: 0.29, face: 'front' } },
  { id: 'BL7', name: 'Tongtian', trad: 'Communication Céleste', info: "Nez bouché chronique, céphalée du vertex.",
    r: { zone: 'tete', h: 0.93, lat: 0.27, face: 'front' } },
  { id: 'BL8', name: 'Luoque', trad: 'Déclin', info: "Vertige, acouphènes, troubles psychiques.",
    r: { zone: 'tete', h: 0.98, lat: 0.24, face: 'front' } },
  { id: 'BL9', name: 'Yuzhen', trad: 'Oreiller de Jade', info: "Occiput. Céphalée, douleur oculaire, nuque raide.",
    r: { zone: 'nuque', lat: 1.3, haut: 2.5 } },
  { id: 'BL11', name: 'Dazhu', trad: 'Grande Navette', info: "Point de réunion des Os. Toux, nuque et dos raides.",
    r: { zone: 'dos', vertebre: 'T1', lat: 1.5, face: 'back' } },
  { id: 'BL12', name: 'Fengmen', trad: 'Porte du Vent', info: "Rhume, toux, fièvre, raideur de nuque.",
    r: { zone: 'dos', vertebre: 'T2', lat: 1.5, face: 'back' } },
  { id: 'BL14', name: 'Jueyinshu', trad: 'Assentiment du Jue Yin', info: "Shu du Péricarde. Douleur cardiaque, oppression.",
    r: { zone: 'dos', vertebre: 'T4', lat: 1.5, face: 'back' } },
  { id: 'BL16', name: 'Dushu', trad: 'Assentiment du Gouverneur', info: "Douleur cardiaque, ballonnement, hoquet.",
    r: { zone: 'dos', vertebre: 'T6', lat: 1.5, face: 'back' } },
  { id: 'BL17', name: 'Geshu', trad: 'Assentiment du Diaphragme', info: "Point de réunion du Sang. Hoquet, anémie, prurit.",
    r: { zone: 'dos', vertebre: 'T7', lat: 1.5, face: 'back' } },
  { id: 'BL19', name: 'Danshu', trad: 'Assentiment de la Vésicule', info: "Ictère, bouche amère, douleur costale.",
    r: { zone: 'dos', vertebre: 'T10', lat: 1.5, face: 'back' } },
  { id: 'BL21', name: 'Weishu', trad: 'Assentiment de l’Estomac', info: "Douleur gastrique, digestion, vomissements.",
    r: { zone: 'dos', vertebre: 'T12', lat: 1.5, face: 'back' } },
  { id: 'BL22', name: 'Sanjiaoshu', trad: 'Assentiment du Triple Réchauffeur', info: "Œdème, borborygmes, lombalgie.",
    r: { zone: 'dos', vertebre: 'L1', lat: 1.5, face: 'back' } },
  { id: 'BL24', name: 'Qihaishu', trad: 'Assentiment de la Mer du Souffle', info: "Lombalgie, hémorroïdes, règles.",
    r: { zone: 'dos', vertebre: 'L3', lat: 1.5, face: 'back' } },
  { id: 'BL26', name: 'Guanyuanshu', trad: 'Assentiment de la Barrière', info: "Lombalgie, diarrhée, urines fréquentes.",
    r: { zone: 'dos', vertebre: 'L5', lat: 1.5, face: 'back' } },
  { id: 'BL27', name: 'Xiaochangshu', trad: 'Assentiment de l’Intestin Grêle', info: "Douleur du bas-ventre, urines, sacrum.",
    r: { zone: 'dos', vertebre: 'S1', lat: 1.5, face: 'back' } },
  { id: 'BL28', name: 'Pangguangshu', trad: 'Assentiment de la Vessie', info: "Rétention, énurésie, lombes et sacrum.",
    r: { zone: 'dos', vertebre: 'S2', lat: 1.5, face: 'back' } },
  { id: 'BL29', name: 'Zhonglushu', trad: 'Assentiment de la Colonne', info: "Lombalgie, sciatique, dysenterie.",
    r: { zone: 'dos', vertebre: 'S3', lat: 1.5, face: 'back' } },
  { id: 'BL30', name: 'Baihuanshu', trad: 'Assentiment de l’Anneau Blanc', info: "Pertes, hémorroïdes, douleur sacrée.",
    r: { zone: 'dos', vertebre: 'S4', lat: 1.5, face: 'back' } },
  { id: 'BL31', name: 'Shangliao', trad: 'Creux Supérieur', info: "1er trou sacré. Lombes, règles, urines.",
    r: { zone: 'dos', vertebre: 'S1', lat: 0.8, face: 'back' } },
  { id: 'BL32', name: 'Ciliao', trad: 'Deuxième Creux', info: "2e trou sacré. Sciatique, règles, accouchement.",
    r: { zone: 'dos', vertebre: 'S2', lat: 0.8, face: 'back' } },
  { id: 'BL33', name: 'Zhongliao', trad: 'Creux du Milieu', info: "3e trou sacré. Constipation, règles, lombes.",
    r: { zone: 'dos', vertebre: 'S3', lat: 0.7, face: 'back' } },
  { id: 'BL34', name: 'Xialiao', trad: 'Creux Inférieur', info: "4e trou sacré. Douleur sacrée, intestins.",
    r: { zone: 'dos', vertebre: 'S4', lat: 0.6, face: 'back' } },
  { id: 'BL35', name: 'Huiyang', trad: 'Réunion du Yang', info: "De part et d'autre du coccyx. Hémorroïdes, diarrhée.",
    r: { zone: 'dos', vertebre: 'S5', lat: 0.5, face: 'back' } },
  { id: 'BL36', name: 'Chengfu', trad: 'Réception du Soutien', info: "Au milieu du pli fessier. Sciatique, hémorroïdes.",
    r: { zone: 'jambe', cun: 0.5, angle: 180 } },
  { id: 'BL37', name: 'Yinmen', trad: 'Porte de l’Abondance', info: "6 cun sous BL36. Lombalgie, sciatique.",
    r: { zone: 'jambe', cun: 7.0, angle: 180 } },
  { id: 'BL38', name: 'Fuxi', trad: 'Fente Superficielle', info: "1 cun au-dessus de BL39. Engourdissement, crampe.",
    r: { zone: 'jambe', cun: 17.0, angle: 195 } },
  { id: 'BL39', name: 'Weiyang', trad: 'Yang Courbé', info: "He inférieur du Triple Réchauffeur. Œdème, rétention, genou.",
    r: { zone: 'jambe', cun: 18.0, angle: 158 } },
  { id: 'BL41', name: 'Fufen', trad: 'Branche Annexe', info: "Nuque et épaule raides, coude.",
    r: { zone: 'dos', vertebre: 'T2', lat: 3, face: 'back' } },
  { id: 'BL42', name: 'Pohu', trad: 'Demeure du Po', info: "Toux, asthme, sueurs nocturnes.",
    r: { zone: 'dos', vertebre: 'T3', lat: 3, face: 'back' } },
  { id: 'BL43', name: 'Gaohuang', trad: 'Centre Vital', info: "Grande tonification. Fatigue profonde, toux chronique.",
    r: { zone: 'dos', vertebre: 'T4', lat: 3, face: 'back' } },
  { id: 'BL44', name: 'Shentang', trad: 'Salle de l’Esprit', info: "Palpitations, oppression, insomnie.",
    r: { zone: 'dos', vertebre: 'T5', lat: 3, face: 'back' } },
  { id: 'BL45', name: 'Yixi', trad: 'Soupir', info: "Toux, douleur d'épaule et de dos.",
    r: { zone: 'dos', vertebre: 'T6', lat: 3, face: 'back' } },
  { id: 'BL46', name: 'Geguan', trad: 'Barrière du Diaphragme', info: "Hoquet, vomissements, dos raide.",
    r: { zone: 'dos', vertebre: 'T7', lat: 3, face: 'back' } },
  { id: 'BL47', name: 'Hunmen', trad: 'Porte du Hun', info: "Douleur costale, vomissements, irritabilité.",
    r: { zone: 'dos', vertebre: 'T9', lat: 3, face: 'back' } },
  { id: 'BL48', name: 'Yanggang', trad: 'Corde du Yang', info: "Ictère, borborygmes, douleur abdominale.",
    r: { zone: 'dos', vertebre: 'T10', lat: 3, face: 'back' } },
  { id: 'BL49', name: 'Yishe', trad: 'Demeure du Yi', info: "Digestion, ballonnement, pensées ruminantes.",
    r: { zone: 'dos', vertebre: 'T11', lat: 3, face: 'back' } },
  { id: 'BL50', name: 'Weicang', trad: 'Grenier de l’Estomac', info: "Douleur gastrique, ballonnement de l'enfant.",
    r: { zone: 'dos', vertebre: 'T12', lat: 3, face: 'back' } },
  { id: 'BL51', name: 'Huangmen', trad: 'Porte du Centre Vital', info: "Constipation, masse abdominale.",
    r: { zone: 'dos', vertebre: 'L1', lat: 3, face: 'back' } },
  { id: 'BL52', name: 'Zhishi', trad: 'Demeure de la Volonté', info: "Lombalgie, impuissance, urines fréquentes.",
    r: { zone: 'dos', vertebre: 'L2', lat: 3, face: 'back' } },
  { id: 'BL53', name: 'Baohuang', trad: 'Centre Vital de la Vessie', info: "Rétention, lombes, distension.",
    r: { zone: 'dos', vertebre: 'S2', lat: 3, face: 'back' } },
  { id: 'BL54', name: 'Zhibian', trad: 'Bord de l’Ordre', info: "Sciatique, hémorroïdes, urines.",
    r: { zone: 'dos', vertebre: 'S4', lat: 3, face: 'back' } },
  { id: 'BL55', name: 'Heyang', trad: 'Yang de l’Union', info: "2 cun sous BL40. Lombalgie, crampe du mollet.",
    r: { zone: 'jambe', cun: 20.0, angle: 180 } },
  { id: 'BL56', name: 'Chengjin', trad: 'Réception des Tendons', info: "Au milieu du mollet. Crampe, hémorroïdes.",
    r: { zone: 'jambe', cun: 23.0, angle: 180 } },
  { id: 'BL58', name: 'Feiyang', trad: 'Envol', info: "Point Luo. Céphalée, lombalgie, hémorroïdes.",
    r: { zone: 'jambe', cun: 27.0, angle: 165 } },
  { id: 'BL59', name: 'Fuyang', trad: 'Yang du Tarse', info: "Céphalée, lombalgie, cheville lourde.",
    r: { zone: 'jambe', cun: 31.0, angle: 150 } },
  { id: 'BL61', name: 'Pucan', trad: 'Serviteur Obéissant', info: "Sous la malléole externe, sur le calcanéum. Talon, faiblesse des jambes.",
    r: { zone: 'jambe', cun: 34.0, angle: 145, bas: 1.4 } },
  { id: 'BL62', name: 'Shenmai', trad: 'Vaisseau de l’Extension', info: "Clé du Yang Qiao Mai. 0,5 cun sous la malléole externe. Insomnie, céphalée, épilepsie.",
    r: { zone: 'jambe', cun: 34.0, angle: 130, bas: 0.7 } },
  { id: 'BL63', name: 'Jinmen', trad: 'Porte de Métal', info: "Point Xi. Convulsions, douleur du pied, lombalgie aiguë.",
    r: { zone: 'pied', avance: 0.34, entre: [5], decal: 0.014, face: 'bord' } },
  { id: 'BL64', name: 'Jinggu', trad: 'Os Capital', info: "Point Yuan. Sous la tubérosité du 5e métatarsien. Céphalée, nuque, épilepsie.",
    r: { zone: 'pied', avance: 0.46, entre: [5], decal: 0.014, face: 'bord' } },
  { id: 'BL65', name: 'Shugu', trad: 'Os Attaché', info: "Point Shu-ruisseau. Céphalée occipitale, nuque raide, vertige.",
    r: { zone: 'pied', avance: 0.68, entre: [5], decal: 0.012, face: 'bord' } },
  { id: 'BL66', name: 'Zutonggu', trad: 'Vallée de Passage', info: "Point Ying-source. Céphalée, vertige, épistaxis.",
    r: { zone: 'pied', orteil: 5, t: 0.2, cote: 'lateral' } },
],

// ------------------------------------------------------------------- Rein
KI: [
  { id: 'KI2', name: 'Rangu', trad: 'Vallée Brûlante', info: "Point Ying-source. Sous la tubérosité naviculaire. Chaleur vide, gorge, règles.",
    r: { zone: 'pied', avance: 0.56, entre: [1], decal: -0.014, face: 'bordOppose' } },
  { id: 'KI4', name: 'Dazhong', trad: 'Grande Cloche', info: "Point Luo. Asthme, rétention, talon douloureux, peur.",
    r: { zone: 'jambe', cun: 34.0, angle: 215, bas: 0.9 } },
  { id: 'KI5', name: 'Shuiquan', trad: 'Source d’Eau', info: "Point Xi. Règles irrégulières, rétention, vue trouble.",
    r: { zone: 'jambe', cun: 34.0, angle: 225, bas: 1.1 } },
  { id: 'KI8', name: 'Jiaoxin', trad: 'Échange de Confiance', info: "Xi du Yin Qiao. Règles irrégulières, métrorragie, diarrhée.",
    r: { zone: 'jambe', cun: 32.0, angle: 248 } },
  { id: 'KI9', name: 'Zhubin', trad: 'Maison de l’Hôte', info: "Xi du Yin Wei. Troubles psychiques, hernie, détoxication.",
    r: { zone: 'jambe', cun: 29.0, angle: 240 } },
  { id: 'KI10', name: 'Yingu', trad: 'Vallée du Yin', info: "Point He-mer. Extrémité interne du pli poplité. Génital, urines, genou.",
    r: { zone: 'jambe', cun: 18.0, angle: 240 } },
  { id: 'KI11', name: 'Henggu', trad: 'Os Transversal', info: "Bord supérieur du pubis. Rétention, impuissance.",
    r: { zone: 'torse', from: 'nombril', cun: 5.0, lat: 0.5, face: 'front' } },
  { id: 'KI12', name: 'Dahe', trad: 'Grande Clarté', info: "Pertes, impuissance, douleur génitale.",
    r: { zone: 'torse', from: 'nombril', cun: 4.0, lat: 0.5, face: 'front' } },
  { id: 'KI13', name: 'Qixue', trad: 'Cavité du Souffle', info: "Stérilité, règles irrégulières, diarrhée.",
    r: { zone: 'torse', from: 'nombril', cun: 3.0, lat: 0.5, face: 'front' } },
  { id: 'KI14', name: 'Siman', trad: 'Quatre Plénitudes', info: "Douleur abdominale, règles, constipation.",
    r: { zone: 'torse', from: 'nombril', cun: 2.0, lat: 0.5, face: 'front' } },
  { id: 'KI15', name: 'Zhongzhu', trad: 'Écoulement Central', info: "Constipation, douleur du bas-ventre.",
    r: { zone: 'torse', from: 'nombril', cun: 1.0, lat: 0.5, face: 'front' } },
  { id: 'KI16', name: 'Huangshu', trad: 'Assentiment des Membranes', info: "À hauteur du nombril. Douleur péri-ombilicale, constipation.",
    r: { zone: 'torse', from: 'nombril', cun: 0.0, lat: 0.5, face: 'front' } },
  { id: 'KI17', name: 'Shangqu', trad: 'Courbure du Commerce', info: "Douleur abdominale, diarrhée, constipation.",
    r: { zone: 'torse', from: 'nombril', cun: -2.0, lat: 0.5, face: 'front' } },
  { id: 'KI18', name: 'Shiguan', trad: 'Barrière de Pierre', info: "Constipation, douleur gastrique, stérilité.",
    r: { zone: 'torse', from: 'nombril', cun: -3.0, lat: 0.5, face: 'front' } },
  { id: 'KI19', name: 'Yindu', trad: 'Capitale du Yin', info: "Ballonnement, vomissements, asthme.",
    r: { zone: 'torse', from: 'nombril', cun: -4.0, lat: 0.5, face: 'front' } },
  { id: 'KI20', name: 'Futonggu', trad: 'Vallée du Passage', info: "Douleur gastrique, vomissements, oppression.",
    r: { zone: 'torse', from: 'nombril', cun: -5.0, lat: 0.5, face: 'front' } },
  { id: 'KI21', name: 'Youmen', trad: 'Porte Sombre', info: "Vomissements, douleur gastrique, mastite.",
    r: { zone: 'torse', from: 'nombril', cun: -6.0, lat: 0.5, face: 'front' } },
  { id: 'KI22', name: 'Bulang', trad: 'Promenade du Corridor', info: "5e espace intercostal. Toux, oppression, inappétence.",
    r: { zone: 'torse', from: 'CV22', cun: 8.2, lat: 2.0, face: 'front' } },
  { id: 'KI23', name: 'Shenfeng', trad: 'Sceau de l’Esprit', info: "4e espace intercostal. Toux, mastite, oppression.",
    r: { zone: 'torse', from: 'CV22', cun: 6.8, lat: 2.0, face: 'front' } },
  { id: 'KI24', name: 'Lingxu', trad: 'Ruines de l’Esprit', info: "3e espace intercostal. Douleur thoracique, toux.",
    r: { zone: 'torse', from: 'CV22', cun: 5.4, lat: 2.0, face: 'front' } },
  { id: 'KI25', name: 'Shencang', trad: 'Grenier de l’Esprit', info: "2e espace intercostal. Toux, asthme, oppression.",
    r: { zone: 'torse', from: 'CV22', cun: 4.0, lat: 2.0, face: 'front' } },
  { id: 'KI26', name: 'Yuzhong', trad: 'Milieu Parfait', info: "1er espace intercostal. Toux, glaires, oppression.",
    r: { zone: 'torse', from: 'CV22', cun: 2.4, lat: 2.0, face: 'front' } },
],

// ------------------------------------------------------ Vésicule Biliaire
GB: [
  { id: 'GB2', name: 'Tinghui', trad: 'Réunion de l’Ouïe', info: "Devant l'échancrure du tragus. Surdité, acouphènes, mâchoire.",
    r: { zone: 'tete', h: 0.4, lat: 0.95, face: 'side', avance: 0.2 } },
  { id: 'GB3', name: 'Shangguan', trad: 'Barrière Supérieure', info: "Au-dessus de l'arcade zygomatique. Migraine, otite, dents.",
    r: { zone: 'tete', h: 0.47, lat: 0.93, face: 'side', avance: 0.24 } },
  { id: 'GB4', name: 'Hanyan', trad: 'Mâchoire Serrée', info: "Migraine temporale, vertige, acouphènes.",
    r: { zone: 'tete', h: 0.72, lat: 0.85, face: 'side', avance: 0.42 } },
  { id: 'GB5', name: 'Xuanlu', trad: 'Crâne Suspendu', info: "Migraine, douleur du coin externe de l'œil.",
    r: { zone: 'tete', h: 0.66, lat: 0.88, face: 'side', avance: 0.35 } },
  { id: 'GB6', name: 'Xuanli', trad: 'Suspension Fine', info: "Migraine, douleur oculaire, fièvre.",
    r: { zone: 'tete', h: 0.61, lat: 0.9, face: 'side', avance: 0.28 } },
  { id: 'GB7', name: 'Qubin', trad: 'Angle de la Tempe', info: "Migraine, trismus, gonflement de la joue.",
    r: { zone: 'tete', h: 0.58, lat: 0.92, face: 'side', avance: 0.16 } },
  { id: 'GB8', name: 'Shuaigu', trad: 'Vallée Directrice', info: "1,5 cun au-dessus de la pointe de l'oreille. Migraine, vertige, nausée.",
    r: { zone: 'tete', h: 0.66, lat: 0.9, face: 'side', avance: 0.0 } },
  { id: 'GB9', name: 'Tianchong', trad: 'Assaut Céleste', info: "Céphalée, gonflement des gencives, convulsions.",
    r: { zone: 'tete', h: 0.66, lat: 0.88, face: 'side', avance: -0.14 } },
  { id: 'GB10', name: 'Fubai', trad: 'Blancheur Flottante', info: "Derrière l'oreille. Acouphènes, mal de dents, épaule.",
    r: { zone: 'tete', h: 0.55, lat: 0.86, face: 'side', avance: -0.26 } },
  { id: 'GB11', name: 'Touqiaoyin', trad: 'Ouverture du Yin', info: "Base de la mastoïde. Surdité, migraine, douleur de langue.",
    r: { zone: 'tete', h: 0.45, lat: 0.85, face: 'side', avance: -0.32 } },
  { id: 'GB12', name: 'Wangu', trad: 'Os Achevé', info: "Derrière la mastoïde. Insomnie, torticolis, paralysie faciale.",
    r: { zone: 'tete', h: 0.36, lat: 0.85, face: 'side', avance: -0.36 } },
  { id: 'GB13', name: 'Benshen', trad: 'Racine de l’Esprit', info: "0,5 cun dans les cheveux, 3 cun de la médiane. Épilepsie, angoisse, vertige.",
    r: { zone: 'tete', h: 0.74, lat: 0.5, face: 'front' } },
  { id: 'GB15', name: 'Toulinqi', trad: 'Larmes de la Tête', info: "Aplomb de la pupille, à la naissance des cheveux. Larmoiement, congestion nasale.",
    r: { zone: 'tete', h: 0.75, lat: 0.31, face: 'front' } },
  { id: 'GB16', name: 'Muchuang', trad: 'Fenêtre de l’Œil', info: "Vue trouble, congestion oculaire, céphalée.",
    r: { zone: 'tete', h: 0.83, lat: 0.3, face: 'front' } },
  { id: 'GB17', name: 'Zhengying', trad: 'Camp Droit', info: "Migraine, mal de dents, vertige.",
    r: { zone: 'tete', h: 0.9, lat: 0.28, face: 'front' } },
  { id: 'GB18', name: 'Chengling', trad: 'Réception de l’Esprit', info: "Céphalée, nez bouché, épistaxis.",
    r: { zone: 'tete', h: 0.96, lat: 0.25, face: 'front' } },
  { id: 'GB19', name: 'Naokong', trad: 'Vide du Cerveau', info: "Au-dessus de GB20, niveau de la protubérance occipitale. Céphalée, raideur de nuque.",
    r: { zone: 'nuque', lat: 2.2, haut: 2.6 } },
  { id: 'GB22', name: 'Yuanye', trad: 'Liquide de l’Aisselle', info: "Ligne axillaire moyenne, 4e espace intercostal. Oppression, douleur costale.",
    r: { zone: 'torse', from: 'CV22', cun: 6.8, lat: 6.0, face: 'side' } },
  { id: 'GB23', name: 'Zhejin', trad: 'Muscle Latéral', info: "1 cun en avant de GB22. Asthme, vomissements acides, douleur costale.",
    r: { zone: 'torse', from: 'CV22', cun: 7.2, lat: 5.6, face: 'side' } },
  { id: 'GB24', name: 'Riyue', trad: 'Soleil et Lune', info: "Point Mu de la Vésicule Biliaire, 7e espace intercostal. Ictère, bouche amère.",
    r: { zone: 'torse', from: 'CV22', cun: 9.6, lat: 4.0, face: 'front' } },
  { id: 'GB25', name: 'Jingmen', trad: 'Porte de la Capitale', info: "Point Mu du Rein, pointe de la 12e côte. Lombalgie, œdème, diarrhée.",
    r: { zone: 'torse', from: 'nombril', cun: -1.5, lat: 6.0, face: 'side' } },
  { id: 'GB26', name: 'Daimai', trad: 'Vaisseau Ceinture', info: "À hauteur du nombril, sous la pointe de la 11e côte. Pertes, règles, lombes.",
    r: { zone: 'torse', from: 'nombril', cun: 0.0, lat: 6.0, face: 'side' } },
  { id: 'GB27', name: 'Wushu', trad: 'Cinquième Pivot', info: "En avant de l'épine iliaque. Pertes, hernie, constipation.",
    r: { zone: 'torse', from: 'nombril', cun: 3.0, lat: 5.5, face: 'front' } },
  { id: 'GB28', name: 'Weidao', trad: 'Voie de la Liaison', info: "0,5 cun sous GB27. Descente d'organe, pertes, douleur pelvienne.",
    r: { zone: 'torse', from: 'nombril', cun: 3.5, lat: 5.5, face: 'front' } },
  { id: 'GB29', name: 'Juliao', trad: 'Grand Creux', info: "Entre l'épine iliaque et le grand trochanter. Hanche, paralysie.",
    r: { zone: 'jambe', cun: 0.5, angle: 95 } },
  { id: 'GB31', name: 'Fengshi', trad: 'Marché du Vent', info: "Là où le majeur touche la cuisse, bras pendant. Sciatique, prurit.",
    r: { zone: 'jambe', cun: 11.0, angle: 100 } },
  { id: 'GB32', name: 'Zhongdu', trad: 'Fossé Central', info: "2 cun sous GB31. Douleur et faiblesse de la cuisse.",
    r: { zone: 'jambe', cun: 13.0, angle: 100 } },
  { id: 'GB33', name: 'Xiyangguan', trad: 'Barrière Yang du Genou', info: "Au-dessus du condyle externe. Genou raide, engourdissement.",
    r: { zone: 'jambe', cun: 16.0, angle: 105 } },
  { id: 'GB35', name: 'Yangjiao', trad: 'Croisement du Yang', info: "Xi du Yang Wei. Oppression, gonflement du visage, jambe.",
    r: { zone: 'jambe', cun: 27.0, angle: 128 } },
  { id: 'GB36', name: 'Waiqiu', trad: 'Tertre Externe', info: "Point Xi. Douleur thoracique, nuque raide, jambe.",
    r: { zone: 'jambe', cun: 27.0, angle: 102 } },
  { id: 'GB37', name: 'Guangming', trad: 'Clarté', info: "Point Luo. Vue trouble, douleur oculaire, jambe.",
    r: { zone: 'jambe', cun: 29.0, angle: 110 } },
  { id: 'GB38', name: 'Yangfu', trad: 'Assistance du Yang', info: "Point Jing-rivière. Migraine, douleur du coin externe de l'œil, sciatique.",
    r: { zone: 'jambe', cun: 30.0, angle: 110 } },
  { id: 'GB41', name: 'Zulinqi', trad: 'Larmes du Pied', info: "Point Shu-ruisseau, clé du Dai Mai. Migraine, règles, douleur costale.",
    r: { zone: 'pied', avance: 0.60, entre: [4, 5] } },
  { id: 'GB42', name: 'Diwuhui', trad: 'Cinq Réunions Terrestres', info: "Douleur du dos du pied, acouphènes, mastite.",
    r: { zone: 'pied', avance: 0.71, entre: [4, 5] } },
  { id: 'GB43', name: 'Xiaxi', trad: 'Ruisseau Étroit', info: "Point Ying-source. Migraine, acouphènes, vertige, fièvre.",
    r: { zone: 'pied', avance: 0.84, entre: [4, 5] } },
  { id: 'GB44', name: 'Zuqiaoyin', trad: 'Ouverture du Yin du Pied', info: "Point Jing-puits. Migraine, insomnie, rêves anxieux, gorge.",
    r: { zone: 'pied', orteil: 4, t: 0.9, cote: 'lateral' } },
],

// ------------------------------------------------ Vaisseau Conception
CV: [
  { id: 'CV1', name: 'Huiyin', trad: 'Réunion des Yin', info: "Au périnée. Réanimation, troubles génitaux et urinaires. Point réservé au praticien.",
    r: { zone: 'perinee' } },
  { id: 'CV2', name: 'Qugu', trad: 'Os Courbe', info: "Bord supérieur du pubis. Rétention, énurésie, impuissance.",
    r: { zone: 'torse', from: 'nombril', cun: 5.0, lat: 0, face: 'front' } },
  { id: 'CV5', name: 'Shimen', trad: 'Porte de Pierre', info: "Point Mu du Triple Réchauffeur. Œdème, diarrhée, règles.",
    r: { zone: 'torse', from: 'nombril', cun: 2.0, lat: 0, face: 'front' } },
  { id: 'CV7', name: 'Yinjiao', trad: 'Croisement du Yin', info: "Règles irrégulières, douleur péri-ombilicale.",
    r: { zone: 'torse', from: 'nombril', cun: 1.0, lat: 0, face: 'front' } },
  { id: 'CV9', name: 'Shuifen', trad: 'Séparation des Eaux', info: "Œdème, rétention d'eau, diarrhée.",
    r: { zone: 'torse', from: 'nombril', cun: -1.0, lat: 0, face: 'front' } },
  { id: 'CV10', name: 'Xiawan', trad: 'Cavité Inférieure', info: "Digestion lente, vomissements, douleur gastrique.",
    r: { zone: 'torse', from: 'nombril', cun: -2.0, lat: 0, face: 'front' } },
  { id: 'CV11', name: 'Jianli', trad: 'Établissement de la Mesure', info: "Inappétence, ballonnement, œdème.",
    r: { zone: 'torse', from: 'nombril', cun: -3.0, lat: 0, face: 'front' } },
  { id: 'CV13', name: 'Shangwan', trad: 'Cavité Supérieure', info: "Vomissements, hoquet, douleur gastrique.",
    r: { zone: 'torse', from: 'nombril', cun: -5.0, lat: 0, face: 'front' } },
  { id: 'CV14', name: 'Juque', trad: 'Grand Palais', info: "Point Mu du Cœur. Palpitations, angoisse, reflux.",
    r: { zone: 'torse', from: 'nombril', cun: -6.0, lat: 0, face: 'front' } },
  { id: 'CV15', name: 'Jiuwei', trad: 'Queue de Tourterelle', info: "Point Luo. Angoisse, palpitations, épilepsie.",
    r: { zone: 'torse', from: 'nombril', cun: -7.0, lat: 0, face: 'front' } },
  { id: 'CV16', name: 'Zhongting', trad: 'Cour Centrale', info: "Base du sternum. Oppression, régurgitations.",
    r: { zone: 'torse', from: 'CV22', cun: 8.0, lat: 0, face: 'front' } },
  { id: 'CV18', name: 'Yutang', trad: 'Salle de Jade', info: "Toux, oppression, vomissements.",
    r: { zone: 'torse', from: 'CV22', cun: 5.4, lat: 0, face: 'front' } },
  { id: 'CV19', name: 'Zigong', trad: 'Palais Pourpre', info: "Toux, asthme, douleur thoracique.",
    r: { zone: 'torse', from: 'CV22', cun: 4.0, lat: 0, face: 'front' } },
  { id: 'CV20', name: 'Huagai', trad: 'Dais Fleuri', info: "Toux, asthme, douleur costale.",
    r: { zone: 'torse', from: 'CV22', cun: 2.4, lat: 0, face: 'front' } },
  { id: 'CV21', name: 'Xuanji', trad: 'Perle Tournante', info: "Toux, oppression, gorge.",
    r: { zone: 'torse', from: 'CV22', cun: 1.0, lat: 0, face: 'front' } },
  { id: 'CV23', name: 'Lianquan', trad: 'Source Anguleuse', info: "Au-dessus de la pomme d'Adam. Aphonie, difficulté à avaler, langue.",
    r: { zone: 'cou', h: 0.86, lat: 0 } },
],

// ------------------------------------------------- Vaisseau Gouverneur
GV: [
  { id: 'GV2', name: 'Yaoshu', trad: 'Assentiment des Lombes', info: "Au hiatus sacré. Lombalgie, hémorroïdes, règles.",
    r: { zone: 'dos', vertebre: 'S4', lat: 0, face: 'back' } },
  { id: 'GV3', name: 'Yaoyangguan', trad: 'Barrière Yang des Lombes', info: "Sous L4. Lombalgie, sciatique, impuissance.",
    r: { zone: 'dos', vertebre: 'L4b', lat: 0, face: 'back' } },
  { id: 'GV5', name: 'Xuanshu', trad: 'Pivot Suspendu', info: "Sous L1. Diarrhée, lombalgie, indigestion.",
    r: { zone: 'dos', vertebre: 'L1', lat: 0, face: 'back' } },
  { id: 'GV6', name: 'Jizhong', trad: 'Centre de la Colonne', info: "Sous T11. Ictère, diarrhée, épilepsie.",
    r: { zone: 'dos', vertebre: 'T11', lat: 0, face: 'back' } },
  { id: 'GV7', name: 'Zhongshu', trad: 'Pivot Central', info: "Sous T10. Douleur gastrique, dos raide.",
    r: { zone: 'dos', vertebre: 'T10', lat: 0, face: 'back' } },
  { id: 'GV8', name: 'Jinsuo', trad: 'Contracture des Tendons', info: "Sous T9. Crampes, épilepsie, dos raide.",
    r: { zone: 'dos', vertebre: 'T9', lat: 0, face: 'back' } },
  { id: 'GV9', name: 'Zhiyang', trad: 'Yang Extrême', info: "Sous T7. Ictère, oppression, dos raide.",
    r: { zone: 'dos', vertebre: 'T7', lat: 0, face: 'back' } },
  { id: 'GV10', name: 'Lingtai', trad: 'Terrasse de l’Esprit', info: "Sous T6. Furoncles, toux, dos.",
    r: { zone: 'dos', vertebre: 'T6', lat: 0, face: 'back' } },
  { id: 'GV11', name: 'Shendao', trad: 'Voie de l’Esprit', info: "Sous T5. Palpitations, anxiété, mauvaise mémoire.",
    r: { zone: 'dos', vertebre: 'T5', lat: 0, face: 'back' } },
  { id: 'GV12', name: 'Shenzhu', trad: 'Pilier du Corps', info: "Sous T3. Toux, asthme, agitation de l'enfant.",
    r: { zone: 'dos', vertebre: 'T3', lat: 0, face: 'back' } },
  { id: 'GV13', name: 'Taodao', trad: 'Voie du Bonheur', info: "Sous T1. Fièvre, frissons, raideur du dos.",
    r: { zone: 'dos', vertebre: 'T1', lat: 0, face: 'back' } },
  { id: 'GV15', name: 'Yamen', trad: 'Porte du Mutisme', info: "0,5 cun au-dessus de la naissance des cheveux. Aphonie, raideur de nuque. Jamais de piqûre profonde.",
    r: { zone: 'nuque', lat: 0, haut: -0.5 } },
  { id: 'GV17', name: 'Naohu', trad: 'Porte du Cerveau', info: "Au-dessus de la protubérance occipitale. Vertige, raideur de nuque.",
    r: { zone: 'crane', arc: 0.8 } },
  { id: 'GV18', name: 'Qiangjian', trad: 'Rigidité Intermédiaire', info: "Céphalée, raideur de nuque, insomnie.",
    r: { zone: 'crane', arc: 0.7 } },
  { id: 'GV19', name: 'Houding', trad: 'Sommet Postérieur', info: "Céphalée du vertex, vertige, insomnie.",
    r: { zone: 'crane', arc: 0.61 } },
  { id: 'GV21', name: 'Qianding', trad: 'Sommet Antérieur', info: "Céphalée, vertige, congestion nasale.",
    r: { zone: 'crane', arc: 0.41 } },
  { id: 'GV22', name: 'Xinhui', trad: 'Réunion de la Fontanelle', info: "Céphalée, vertige, nez bouché.",
    r: { zone: 'crane', arc: 0.32 } },
  { id: 'GV23', name: 'Shangxing', trad: 'Étoile Supérieure', info: "1 cun dans les cheveux. Nez bouché, épistaxis, céphalée frontale.",
    r: { zone: 'crane', arc: 0.24 } },
  { id: 'GV24', name: 'Shenting', trad: 'Cour de l’Esprit', info: "0,5 cun dans les cheveux. Anxiété, insomnie, céphalée.",
    r: { zone: 'crane', arc: 0.2 } },
  { id: 'GV25', name: 'Suliao', trad: 'Creux Simple', info: "À la pointe du nez. Réanimation, épistaxis, rhinite.",
    r: { zone: 'tete', h: 0.365, lat: 0, face: 'front' } },
  { id: 'GV27', name: 'Duiduan', trad: 'Extrémité de la Bouche', info: "Au bord supérieur de la lèvre. Convulsions, gencives, soif.",
    r: { zone: 'tete', h: 0.225, lat: 0, face: 'front' } },
  { id: 'GV28', name: 'Yinjiao', trad: 'Croisement des Gencives', info: "Au frein de la lèvre supérieure. Gencives, rhinite, troubles mentaux.",
    r: { zone: 'tete', h: 0.205, lat: 0, face: 'front' } },
],
};

if (typeof module !== 'undefined') module.exports = { CATALOGUE };
