// Localisation canonique de chaque point, et comment le trouver sur soi.
//
// `loc`     : la localisation telle que l'énoncent les manuels — repère osseux
//             et distance en cun. C'est ce que reprennent les cotes des
//             planches 2D.
// `trouver` : la même chose, mais du point de vue de la main qui cherche.
//             Un point ne se trouve pas avec une règle : on suit un tendon, on
//             plie une articulation, on cherche le creux qui répond.
// `prudence`: contre-indications à connaître.
//
// Le « cun » est proportionnel au corps de la personne : 1 cun = la largeur du
// pouce à l'articulation ; 3 cun = les quatre doigts serrés, mesurés au pli de
// l'index. On mesure toujours sur le corps que l'on traite.

const REPERAGE = {
  // ---------------- Poumon ----------------
  LU1: { loc: "Sous la clavicule, dans le 1er espace intercostal, à 6 cun de la ligne médiane.",
    trouver: "Glissez les doigts sous la clavicule vers l'épaule : ils butent dans un creux, juste en dedans de l'articulation." },
  LU5: { loc: "Au pli du coude, sur le bord radial du tendon du biceps.",
    trouver: "Pliez le coude : le tendon dur au milieu du pli. Le point est juste à côté, du côté du pouce." },
  LU6: { loc: "7 cun au-dessus du pli du poignet, sur la ligne LU5–LU9.",
    trouver: "Au milieu de l'avant-bras côté pouce, un peu plus près du coude que du poignet." },
  LU7: { loc: "1,5 cun au-dessus du pli du poignet, dans l'échancrure du bord radial.",
    trouver: "Croisez les deux mains par les pouces écartés, index tendu : l'index tombe sur une petite fente osseuse. C'est là." },
  LU9: { loc: "Au pli du poignet, dans le creux au bord externe de l'artère radiale.",
    trouver: "Là où l'on prend le pouls, mais juste à côté de l'artère, contre l'os." },
  LU10: { loc: "Au milieu du 1er métacarpien, à la limite peau claire / peau foncée de l'éminence thénar.",
    trouver: "Sur la tranche du renflement charnu à la base du pouce, à mi-longueur." },
  LU11: { loc: "Au coin de l'ongle du pouce, côté radial, à 0,1 cun de l'angle.",
    trouver: "Coin de l'ongle du pouce, du côté opposé à l'index." },

  // ---------------- Gros Intestin ----------------
  LI1: { loc: "Angle de l'ongle de l'index, côté radial (vers le pouce).",
    trouver: "Coin de l'ongle de l'index, du côté du pouce." },
  LI4: { loc: "Sur le dos de la main, au milieu du 2e métacarpien, sur son bord radial.",
    trouver: "Serrez le pouce contre l'index : un muscle bombe entre les deux. Le point est au sommet de ce bombement, contre l'os de l'index.",
    prudence: "À éviter pendant la grossesse." },
  LI10: { loc: "2 cun sous le pli du coude, sur la ligne LI11–LI5.",
    trouver: "Trois travers de doigt sous le pli du coude, sur le muscle de la face externe qui se durcit quand on serre le poing." },
  LI11: { loc: "À l'extrémité externe du pli du coude, coude fléchi.",
    trouver: "Pliez le coude complètement : le point est au bout du pli, du côté du pouce." },
  LI14: { loc: "À l'insertion inférieure du deltoïde, sur la face externe du bras.",
    trouver: "Descendez le long du deltoïde : le point est à sa pointe, là où le muscle s'attache à l'os." },
  LI15: { loc: "Dans la dépression antérieure sous l'acromion, bras en abduction.",
    trouver: "Levez le bras à l'horizontale : deux creux se forment sur l'épaule. LI15 est celui de devant." },
  LI20: { loc: "Dans le sillon naso-génien, à mi-hauteur de l'aile du nez.",
    trouver: "Dans le pli qui descend du nez vers la bouche, à hauteur du bord de la narine." },

  // ---------------- Estomac ----------------
  ST1: { loc: "Entre le globe oculaire et le rebord orbitaire inférieur, à l'aplomb de la pupille.",
    trouver: "Regard droit devant : juste sous l'œil, contre l'os.",
    prudence: "Zone fragile : pression très légère, jamais d'aiguille sans formation." },
  ST2: { loc: "Dans le trou sous-orbitaire, 1 cun sous ST1.",
    trouver: "Un travers de doigt sous l'œil : le doigt trouve un petit trou dans l'os, souvent sensible." },
  ST6: { loc: "Sur le muscle masséter, à un travers de doigt en avant et au-dessus de l'angle de la mâchoire.",
    trouver: "Serrez les dents : le muscle qui bombe sur la joue. Relâchez, puis appuyez au sommet du renflement." },
  ST8: { loc: "À l'angle frontal de la ligne des cheveux, 0,5 cun dans les cheveux.",
    trouver: "Au coin du front, juste au-dessus de la naissance des cheveux." },
  ST25: { loc: "À 2 cun de part et d'autre du centre du nombril.",
    trouver: "Trois travers de doigt de côté à partir du nombril." },
  ST36: { loc: "3 cun sous le bord inférieur de la rotule, à un travers de doigt en dehors de la crête tibiale.",
    trouver: "Paume sur la rotule, doigts vers le bas : le point tombe sous l'auriculaire, à un doigt en dehors de l'os. Il répond en dur sous la pression." },
  ST40: { loc: "8 cun sous le bord inférieur de la rotule, à deux travers de doigt en dehors de la crête tibiale.",
    trouver: "À mi-chemin exactement entre le genou et la cheville, sur le muscle en dehors du tibia." },
  ST44: { loc: "Sur le dos du pied, en avant de la commissure des 2e et 3e orteils.",
    trouver: "Dans le creux juste devant l'écart entre le 2e et le 3e orteil." },
  ST45: { loc: "Angle de l'ongle du 2e orteil, côté externe.",
    trouver: "Coin de l'ongle du deuxième orteil, du côté du petit orteil." },

  // ---------------- Rate ----------------
  SP1: { loc: "Angle de l'ongle du gros orteil, côté interne.",
    trouver: "Coin de l'ongle du gros orteil, du côté de l'autre pied." },
  SP3: { loc: "Bord interne du pied, en arrière et en dessous de la tête du 1er métatarsien.",
    trouver: "Suivez la tranche interne du pied vers le talon : le doigt bute derrière la grosse articulation du gros orteil." },
  SP6: { loc: "3 cun au-dessus de la pointe de la malléole interne, au bord postérieur du tibia.",
    trouver: "Quatre doigts serrés au-dessus de l'os de la cheville, côté interne ; le point est juste derrière le bord du tibia.",
    prudence: "Interdit pendant la grossesse." },
  SP9: { loc: "Dans la dépression sous le condyle interne du tibia.",
    trouver: "Remontez le bord interne du tibia avec le pouce : il s'arrête dans un creux, sous le genou." },
  SP10: { loc: "2 cun au-dessus du bord supérieur interne de la rotule, sur le vaste interne.",
    trouver: "Genou plié, posez la paume opposée sur la rotule : le pouce écarté tombe sur le point, sur le muscle bombé." },
  SP21: { loc: "Sur la ligne axillaire moyenne, dans le 6e espace intercostal.",
    trouver: "Bras levé, descendez du creux de l'aisselle le long du flanc : à peu près à mi-hauteur des côtes." },

  // ---------------- Cœur ----------------
  HT1: { loc: "Au centre du creux axillaire, au bord interne de l'artère.",
    trouver: "Bras levé : au fond de l'aisselle, là où le pouls se sent." },
  HT3: { loc: "À l'extrémité interne du pli du coude, coude fléchi.",
    trouver: "Pliez le coude : le point est au bout du pli, du côté de l'auriculaire." },
  HT5: { loc: "1 cun au-dessus du pli du poignet, au bord radial du tendon fléchisseur ulnaire.",
    trouver: "Un travers de pouce au-dessus du pli, dans le prolongement de l'auriculaire." },
  HT7: { loc: "Au pli du poignet, au bord radial du tendon fléchisseur ulnaire.",
    trouver: "Descendez la ligne de l'auriculaire jusqu'au pli du poignet : le creux juste avant le petit os rond." },
  HT9: { loc: "Angle de l'ongle de l'auriculaire, côté radial (vers l'annulaire).",
    trouver: "Coin de l'ongle du petit doigt, du côté de l'annulaire." },

  // ---------------- Intestin Grêle ----------------
  SI1: { loc: "Angle de l'ongle de l'auriculaire, côté ulnaire (bord de la main).",
    trouver: "Coin de l'ongle du petit doigt, du côté extérieur de la main." },
  SI3: { loc: "Bord ulnaire de la main, en arrière de la tête du 5e métacarpien.",
    trouver: "Fermez le poing sans serrer : un pli se forme sur la tranche de la main. Le point est au bout de ce pli." },
  SI8: { loc: "Entre l'olécrâne et l'épicondyle médial, coude fléchi.",
    trouver: "Le « petit juif » : le sillon où passe le nerf, entre les deux os de la pointe du coude." },
  SI11: { loc: "Au centre de la fosse sous-épineuse de l'omoplate.",
    trouver: "Au milieu de la partie charnue de l'omoplate, sous son épine. Souvent très sensible." },
  SI18: { loc: "Au bord inférieur de l'os malaire, à l'aplomb de l'angle externe de l'œil.",
    trouver: "Sous la pommette, à la verticale du coin externe de l'œil." },
  SI19: { loc: "Devant le tragus, dans la dépression qui apparaît bouche ouverte.",
    trouver: "Doigt devant l'oreille, ouvrez la bouche : un creux se forme sous le doigt." },

  // ---------------- Vessie ----------------
  BL1: { loc: "0,1 cun au-dessus de l'angle interne de l'œil.",
    trouver: "Au coin interne de l'œil, contre l'os du nez.",
    prudence: "Zone fragile : pression très légère." },
  BL2: { loc: "À l'extrémité interne du sourcil, dans l'encoche sus-orbitaire.",
    trouver: "Au début du sourcil, côté nez : le doigt trouve une petite encoche dans l'os." },
  BL10: { loc: "1,3 cun de part et d'autre de la ligne médiane, sous l'occiput, au bord externe du trapèze.",
    trouver: "Sur les deux cordes musculaires de la nuque, juste sous le crâne." },
  BL13: { loc: "1,5 cun de part et d'autre du bord inférieur de l'apophyse épineuse de T3. Point Shu du Poumon." },
  BL15: { loc: "1,5 cun de part et d'autre de T5. Point Shu du Cœur." },
  BL18: { loc: "1,5 cun de part et d'autre de T9. Point Shu du Foie." },
  BL20: { loc: "1,5 cun de part et d'autre de T11. Point Shu de la Rate." },
  BL23: { loc: "1,5 cun de part et d'autre de L2, à hauteur du nombril. Point Shu du Rein.",
    trouver: "Mains sur les hanches, pouces vers la colonne : les pouces tombent à peu près sur les deux points." },
  BL25: { loc: "1,5 cun de part et d'autre de L4, à hauteur des crêtes iliaques. Point Shu du Gros Intestin." },
  BL40: { loc: "Au milieu du pli poplité, entre les deux tendons.",
    trouver: "Au centre exact du creux derrière le genou." },
  BL57: { loc: "8 cun sous BL40, à la pointe du V que forment les deux chefs du mollet.",
    trouver: "Montez sur la pointe des pieds : le mollet dessine un V. Le point est à la pointe du V." },
  BL60: { loc: "Entre la pointe de la malléole externe et le tendon d'Achille.",
    trouver: "Le creux entre l'os de la cheville, côté extérieur, et le tendon." },
  BL67: { loc: "Angle de l'ongle du 5e orteil, côté externe.",
    trouver: "Coin de l'ongle du petit orteil, du côté extérieur.",
    prudence: "À éviter pendant la grossesse, sauf indication obstétricale." },

  // ---------------- Rein ----------------
  KI1: { loc: "À la plante, au tiers antérieur de la ligne talon–commissure des 2e et 3e orteils.",
    trouver: "Repliez les orteils : un creux se forme au milieu de la plante, juste derrière le coussinet. C'est là." },
  KI3: { loc: "Entre la pointe de la malléole interne et le tendon d'Achille.",
    trouver: "Le creux entre l'os de la cheville, côté intérieur, et le tendon. On y sent battre une artère." },
  KI6: { loc: "1 cun sous la pointe de la malléole interne.",
    trouver: "Juste sous l'os de la cheville côté interne, dans le petit creux." },
  KI7: { loc: "2 cun au-dessus de KI3, au bord antérieur du tendon d'Achille.",
    trouver: "Deux travers de doigt au-dessus de KI3, en montant le long du tendon." },
  KI27: { loc: "Sous le bord inférieur de la clavicule, à 2 cun de la ligne médiane.",
    trouver: "Sous la clavicule, à trois doigts du milieu du sternum." },

  // ---------------- Maître du Cœur ----------------
  PC3: { loc: "Au pli du coude, au bord ulnaire du tendon du biceps.",
    trouver: "Pliez le coude : le tendon au milieu du pli ; le point est de l'autre côté que LU5, vers l'auriculaire." },
  PC6: { loc: "2 cun au-dessus du pli du poignet, entre les tendons du long palmaire et du fléchisseur radial.",
    trouver: "Trois doigts serrés au-dessus du pli du poignet, au milieu : les deux cordes tendineuses encadrent le point." },
  PC7: { loc: "Au milieu du pli du poignet, entre les deux mêmes tendons.",
    trouver: "Exactement au centre du pli du poignet, face interne." },
  PC8: { loc: "Au centre de la paume, entre les 2e et 3e métacarpiens.",
    trouver: "Fermez le poing : le point est là où la pointe du majeur touche la paume." },
  PC9: { loc: "À la pointe du majeur, à 0,1 cun de l'ongle.",
    trouver: "Tout au bout du majeur." },

  // ---------------- Triple Réchauffeur ----------------
  TE3: { loc: "Sur le dos de la main, dans le creux en arrière des têtes des 4e et 5e métacarpiens.",
    trouver: "Poing fermé : glissez le doigt entre l'annulaire et l'auriculaire vers le poignet ; il bute dans un creux." },
  TE5: { loc: "2 cun au-dessus du pli du poignet, face dorsale, entre radius et ulna.",
    trouver: "Exactement à l'opposé de PC6, de l'autre côté du bras : pincez l'avant-bras entre pouce et index." },
  TE14: { loc: "Dans la dépression postérieure sous l'acromion, bras en abduction.",
    trouver: "Levez le bras à l'horizontale : des deux creux de l'épaule, TE14 est celui de derrière." },
  TE17: { loc: "Derrière le lobe de l'oreille, dans le creux entre la mastoïde et la mandibule.",
    trouver: "Rabattez le lobe en arrière : le point est dans le creux qu'il recouvre." },
  TE23: { loc: "Dans la dépression à l'extrémité externe du sourcil.",
    trouver: "Au bout du sourcil, côté tempe, dans le petit creux osseux." },

  // ---------------- Vésicule Biliaire ----------------
  GB1: { loc: "0,5 cun en dehors de l'angle externe de l'œil, dans la dépression osseuse.",
    trouver: "Un demi-pouce en dehors du coin externe de l'œil, contre l'os." },
  GB14: { loc: "1 cun au-dessus du milieu du sourcil.",
    trouver: "Regard droit devant : un travers de pouce au-dessus du milieu du sourcil, à l'aplomb de la pupille." },
  GB20: { loc: "Sous l'occiput, dans le creux entre le trapèze et le sterno-cléido-mastoïdien.",
    trouver: "Mains croisées derrière la tête, pouces sous le crâne : ils tombent dans deux creux marqués." },
  GB21: { loc: "Au sommet de l'épaule, à mi-distance entre l'apophyse de C7 et l'acromion.",
    trouver: "Au point le plus haut du trapèze, là où l'on pose spontanément la main quand la nuque est prise.",
    prudence: "Interdit pendant la grossesse." },
  GB30: { loc: "Au tiers externe de la ligne joignant le grand trochanter au hiatus sacré.",
    trouver: "Debout, jambe fléchie : un creux se forme sur la fesse, en dehors. Il faut appuyer fort, le muscle est épais." },
  GB34: { loc: "Dans la dépression en avant et sous la tête du péroné.",
    trouver: "Le petit os rond en dehors, sous le genou : le point est juste devant et dessous." },
  GB39: { loc: "3 cun au-dessus de la pointe de la malléole externe, au bord antérieur du péroné.",
    trouver: "Quatre doigts au-dessus de l'os de la cheville, côté externe, contre le bord avant de l'os." },
  GB40: { loc: "En avant et en dessous de la malléole externe, dans la dépression du tendon extenseur.",
    trouver: "En avant de l'os de la cheville côté externe, dans le creux." },

  // ---------------- Foie ----------------
  LR1: { loc: "Angle de l'ongle du gros orteil, côté externe.",
    trouver: "Coin de l'ongle du gros orteil, du côté du 2e orteil." },
  LR2: { loc: "Sur le dos du pied, en avant de la commissure des 1er et 2e orteils.",
    trouver: "Juste devant l'écart entre le gros orteil et le deuxième." },
  LR3: { loc: "Sur le dos du pied, dans le creux entre les 1er et 2e métatarsiens.",
    trouver: "Glissez le doigt entre le gros orteil et le 2e en remontant vers la cheville : il bute dans un V osseux." },
  LR8: { loc: "À l'extrémité interne du pli poplité, genou fléchi.",
    trouver: "Pliez le genou : le point est au bout du pli, côté intérieur, en avant des tendons." },
  LR14: { loc: "Dans le 6e espace intercostal, à 4 cun de la ligne médiane, à l'aplomb du mamelon.",
    trouver: "Descendez de deux espaces sous le mamelon, entre les côtes." },

  // ---------------- Vaisseau Conception ----------------
  CV3: { loc: "Sur la ligne médiane, 4 cun sous le nombril, soit 1 cun au-dessus du pubis.",
    prudence: "Vider la vessie avant de traiter." },
  CV4: { loc: "Sur la ligne médiane, 3 cun sous le nombril.",
    trouver: "Quatre doigts serrés sous le nombril, sur la ligne médiane." },
  CV6: { loc: "Sur la ligne médiane, 1,5 cun sous le nombril.",
    trouver: "Deux travers de doigt sous le nombril." },
  CV8: { loc: "Au centre du nombril.",
    prudence: "Jamais d'aiguille : moxibustion ou pression seulement." },
  CV12: { loc: "Sur la ligne médiane, 4 cun au-dessus du nombril, à mi-chemin du creux de l'estomac.",
    trouver: "À mi-distance exacte entre le nombril et la pointe du sternum." },
  CV17: { loc: "Sur le sternum, au niveau du 4e espace intercostal, à mi-distance des mamelons.",
    trouver: "Au milieu du sternum, à hauteur des mamelons : l'os répond creux." },
  CV22: { loc: "Au centre du creux sus-sternal, au-dessus du manubrium.",
    trouver: "Le creux au bas de la gorge, entre les deux clavicules.",
    prudence: "Pression douce et perpendiculaire seulement." },
  CV24: { loc: "Au milieu du sillon labio-mentonnier.",
    trouver: "Dans le pli entre la lèvre inférieure et le menton." },

  // ---------------- Vaisseau Gouverneur ----------------
  GV1: { loc: "À mi-distance entre la pointe du coccyx et l'anus." },
  GV4: { loc: "Sous l'apophyse épineuse de L2, sur la ligne médiane.",
    trouver: "Dans le creux de la colonne, à hauteur du nombril — juste entre les deux points BL23." },
  GV14: { loc: "Sous l'apophyse épineuse de C7, sur la ligne médiane.",
    trouver: "Penchez la tête en avant : la vertèbre la plus saillante de la nuque. Le point est juste dessous." },
  GV16: { loc: "1 cun au-dessus de la naissance des cheveux, dans le creux sous l'occiput.",
    trouver: "Sur la ligne médiane, dans le creux au bas du crâne.",
    prudence: "Ne jamais piquer profondément ni vers le haut." },
  GV20: { loc: "Au sommet du crâne, à l'intersection de la ligne médiane et de la ligne joignant les pointes des oreilles.",
    trouver: "Remontez les deux pouces depuis le sommet des oreilles : ils se rejoignent sur le point, dans une légère dépression." },
  GV26: { loc: "Au tiers supérieur du sillon sous-nasal.",
    trouver: "Dans la gouttière entre le nez et la lèvre, plus près du nez." },
};

if (typeof module !== 'undefined') module.exports = { REPERAGE };
